
      
import { PlaceHolderImages, ImagePlaceholder } from "@/lib/placeholder-images";

export type Spec = {
  label: string;
  value: string;
};

export type Trim = {
  name: string;
  price: number;
  specs: Spec[];
};

export type SeoText = {
    title: string;
    description: string;
    audience: string;
}

export type Car = {
  id: string;
  name:string;
  price: number;
  monthly: number;
  info: string;
  images: ImagePlaceholder[];
  gearbox: 'механическая' | 'робот' | 'автомат' | 'вариатор';
  bodyType: 'хечбек' | 'внедорожник' | 'седан';
  count: number;
  seats: number;
  specs: Spec[];
  trims: Trim[];
  seoText?: SeoText;
  trimName?: string;
  year?: number;
  engineVolume?: string;
  transmission?: 'Механическая' | 'Робот' | 'Вариатор';
  drivetrain?: 'Передний привод' | 'Полный привод';
  status?: 'У дилера' | 'В пути' | 'Центральный склад';
  dealer?: string;
  color?: string;
  vin?: string;
};

export type Model = {
    id: string;
    name: string;
    description: string;
    image: ImagePlaceholder;
    price: number;
    link: string;
}

export const allModels: Model[] = [
    {
        id: 't4',
        name: 'Tenet T4',
        description: 'Компактный городской кроссовер для тех, кто живет в ритме мегаполиса. Стильный дизайн, маневренность и экономичный расход топлива делают его идеальным спутником в плотном трафике.',
        image: PlaceHolderImages.find((img) => img.id === 'tenet-4')!,
        price: 1999000,
        link: '/models/tenet-t4-mt-line-white'
    },
    {
        id: 't7',
        name: 'Tenet T7',
        description: 'Вместительный и надежный внедорожник, созданный для путешествий и семейных поездок. Мощный двигатель, просторный салон и богатое оснащение обеспечивают комфорт и безопасность.',
        image: PlaceHolderImages.find((img) => img.id === 'tenet-7')!,
        price: 2630000,
        link: '/models/vin-EDEFB32BSE---01'
    },
    {
        id: 't8',
        name: 'Tenet T8',
        description: 'Яркий и технологичный лифтбек для тех, кто ценит динамику и передовые решения. Футуристичный дизайн, впечатляющая мощность и интеллектуальные системы помощи водителю.',
        image: PlaceHolderImages.find((img) => img.id === 'tenet-8')!,
        price: 3399900,
        link: '/models/tenet-t8-premium-sport-blue'
    }
];


export const allCars: Car[] = [
  {
    id: "vin-EDEEB11BSE---99",
    name: "Tenet T4",
    price: 1999000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-5")!,
    ],
    gearbox: "механическая",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "MT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Механическая",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEEB11B*SE****99"
  },
  {
    id: "vin-EDEEB11BSE---02",
    name: "Tenet T4",
    price: 1999000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-5")!,
    ],
    gearbox: "механическая",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "MT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Механическая",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Искрящийся белый",
    vin: "EDEEB11B*SE****02"
  },
  {
    id: "vin-EDEEB41BSE---81",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-5")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Глубокий черный",
    vin: "EDEEB41B*SE****81"
  },
  {
    id: "vin-EDEEB41BSE---21",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-4")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Технологичный серый",
    vin: "EDEEB41B*SE****21"
  },
  {
    id: "vin-EDEEB41BSE---30",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-5")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "В пути",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEEB41B*SE****30"
  },
  {
    id: "vin-EDEEB41BSE---28",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-5")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEEB41B*SE****28"
  },
  {
    id: "vin-EDEEB41BSE---35",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-5")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEEB41B*SE****35"
  },
  {
    id: "vin-EDEEB41BSE---00",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-5")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEEB41B*SE****00"
  },
  {
    id: "vin-EDEEB41BSE---98",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-5")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEEB41B*SE****98"
  },
  {
    id: "vin-EDEEB41BSE---69",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-white-5")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEEB41B*SE****69"
  },
  {
    id: "vin-EDEEB41BSE---55",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-5")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Глубокий черный",
    vin: "EDEEB41B*SE****55"
  },
  {
    id: "vin-EDEEB41BSE---54",
    name: "Tenet T4",
    price: 2129000,
    monthly: 0,
    info: "1 автомобиль",
    images: [
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-1")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-2")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-3")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-4")!,
        PlaceHolderImages.find((img) => img.id === "tenet-t4-black-5")!,
    ],
    gearbox: "вариатор",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "CVT Line",
    year: 2024,
    engineVolume: "1.5",
    transmission: "Вариатор",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Глубокий черный",
    vin: "EDEEB41B*SE****54"
  },
  {
    id: "vin-EDEEB31BSE---30",
    name: "Tenet T4",
    price: 2250000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t4-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "Active",
    year: 2024,
    engineVolume: "1.5T",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Искрящийся белый",
    vin: "EDEEB31B*SE****30"
  },
  {
    id: "vin-EDEEB31BSE---08",
    name: "Tenet T4",
    price: 2250000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t4-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "Active",
    year: 2024,
    engineVolume: "1.5T",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEEB31B*SE****08"
  },
  {
    id: "vin-EDEEB31BSE---44",
    name: "Tenet T4",
    price: 2250000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t4-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "Active",
    year: 2024,
    engineVolume: "1.5T",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Искрящийся белый",
    vin: "EDEEB31B*SE****44"
  },
  {
    id: "vin-EDEEB31BSE---70",
    name: "Tenet T4",
    price: 2250000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t4-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "Active",
    year: 2024,
    engineVolume: "1.5T",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Искрящийся белый",
    vin: "EDEEB31B*SE****70"
  },
  {
    id: "vin-EDEEB31BSE---18",
    name: "Tenet T4",
    price: 2250000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t4-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "Active",
    year: 2024,
    engineVolume: "1.5T",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Искрящийся белый",
    vin: "EDEEB31B*SE****18"
  },
  {
    id: "vin-EDEEB31BSE---56",
    name: "Tenet T4",
    price: 2380000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t4-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "Prime",
    year: 2024,
    engineVolume: "1.5T",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Искрящийся белый",
    vin: "EDEEB31B*SE****56"
  },
  {
    id: "vin-EDEEB31BSE---04",
    name: "Tenet T4",
    price: 2380000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t4-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: "Prime",
    year: 2024,
    engineVolume: "1.5T",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Искрящийся белый",
    vin: "EDEEB31B*SE****04"
  },
  {
    id: "vin-EDEFB32BSE---01",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-silver-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Технологичный серый",
    vin: "EDEFB32B*SE****01"
  },
  {
    id: "vin-EDEFB32BSE---05",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****05"
  },
  {
    id: "vin-EDEFB32BSE---87",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-black-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Глубокий черный",
    vin: "EDEFB32B*SE****87"
  },
  {
    id: "vin-EDEFB32BSE---14",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****14"
  },
  {
    id: "vin-EDEFB32BSE---32",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****32"
  },
  {
    id: "vin-EDEFB32BSE---24",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****24"
  },
  {
    id: "vin-EDEFB32BSE---74",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****74"
  },
  {
    id: "vin-EDEFB32BSE---10",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****10"
  },
  {
    id: "vin-EDEFB32BSE---22",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****22"
  },
  {
    id: "vin-EDEFB32BSE---78",
    name: "Tenet T7",
    price: 2630000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-black-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Active 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Глубокий черный",
    vin: "EDEFB32B*SE****78"
  },
  {
    id: "vin-EDEFB32BSE---59",
    name: "Tenet T7",
    price: 2830000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-silver-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Prime 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Технологичный серый",
    vin: "EDEFB32B*SE****59"
  },
  {
    id: "vin-EDEFB32BSE---07",
    name: "Tenet T7",
    price: 2830000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Prime 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****07"
  },
  {
    id: "vin-EDEFB32BSE---04-t7-prime",
    name: "Tenet T7",
    price: 2830000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Prime 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****04"
  },
  {
    id: "vin-EDEFB32BSE---08-t7-prime",
    name: "Tenet T7",
    price: 2830000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-silver-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Prime 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ОПТИМА",
    color: "Технологичный серый",
    vin: "EDEFB32B*SE****08"
  },
  {
    id: "vin-EDEFB32BSE---02-t7-prime",
    name: "Tenet T7",
    price: 2830000,
    monthly: 0,
    info: "1 автомобиль",
    images: [ PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')! ],
    gearbox: "робот",
    bodyType: "внедорожник",
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: "Prime 2WD",
    year: 2024,
    engineVolume: "1.6",
    transmission: "Робот",
    drivetrain: "Передний привод",
    status: "У дилера",
    dealer: "ЛЕОН-АВТО",
    color: "Искрящийся белый",
    vin: "EDEFB32B*SE****02"
  },
  {
    id: 'vin-EDEGD34B*SE****39',
    name: 'Tenet T8',
    price: 3640000,
    monthly: 0,
    info: '1 автомобиль',
    images: [PlaceHolderImages.find(p => p.id === 'tenet-t8-main')!],
    gearbox: 'робот',
    bodyType: 'внедорожник',
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: 'Ultra',
    year: 2024,
    engineVolume: '2.0T',
    transmission: 'Робот',
    drivetrain: 'Полный привод',
    status: 'У дилера',
    dealer: 'ОПТИМА',
    color: 'Искрящийся белый',
    vin: 'EDEGD34B*SE****39',
  },
  {
    id: 'vin-EDEGD34B*SE****13',
    name: 'Tenet T8',
    price: 3640000,
    monthly: 0,
    info: '1 автомобиль',
    images: [PlaceHolderImages.find(p => p.id === 'tenet-t8-main')!],
    gearbox: 'робот',
    bodyType: 'внедорожник',
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: 'Ultra',
    year: 2024,
    engineVolume: '2.0T',
    transmission: 'Робот',
    drivetrain: 'Полный привод',
    status: 'Центральный склад',
    dealer: 'Склад (ОПТИМА)',
    color: 'Искрящийся белый',
    vin: 'EDEGD34B*SE****13',
  },
  {
    id: 'vin-EDEFD32B*SE****04',
    name: 'Tenet T7',
    price: 3030000,
    monthly: 0,
    info: '1 автомобиль',
    images: [PlaceHolderImages.find(p => p.id === 'tenet-t7-black-1')!],
    gearbox: 'робот',
    bodyType: 'внедорожник',
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: 'Prime',
    year: 2024,
    engineVolume: '1.6',
    transmission: 'Робот',
    drivetrain: 'Полный привод',
    status: 'У дилера',
    dealer: 'ОПТИМА',
    color: 'Глубокий черный',
    vin: 'EDEFD32B*SE****04',
  },
  {
    id: 'vin-EDEFD32B*SE****18',
    name: 'Tenet T7',
    price: 3030000,
    monthly: 0,
    info: '1 автомобиль',
    images: [PlaceHolderImages.find(p => p.id === 'tenet-t7-black-1')!],
    gearbox: 'робот',
    bodyType: 'внедорожник',
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: 'Prime',
    year: 2024,
    engineVolume: '1.6',
    transmission: 'Робот',
    drivetrain: 'Полный привод',
    status: 'У дилера',
    dealer: 'ОПТИМА',
    color: 'Глубокий черный',
    vin: 'EDEFD32B*SE****18',
  },
  {
    id: 'vin-EDEFB32B*SE****47',
    name: 'Tenet T7',
    price: 2830000,
    monthly: 0,
    info: '1 автомобиль',
    images: [PlaceHolderImages.find(p => p.id === 'tenet-t7-silver-1')!],
    gearbox: 'робот',
    bodyType: 'внедорожник',
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: 'Prime',
    year: 2024,
    engineVolume: '1.6',
    transmission: 'Робот',
    drivetrain: 'Передний привод',
    status: 'У дилера',
    dealer: 'ОПТИМА',
    color: 'Серебристый',
    vin: 'EDEFB32B*SE****47',
  },
  {
    id: 'vin-EDEFB32B*SE****80',
    name: 'Tenet T7',
    price: 2830000,
    monthly: 0,
    info: '1 автомобиль',
    images: [PlaceHolderImages.find(p => p.id === 'tenet-t7-silver-1')!],
    gearbox: 'робот',
    bodyType: 'внедорожник',
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: 'Prime',
    year: 2024,
    engineVolume: '1.6',
    transmission: 'Робот',
    drivetrain: 'Передний привод',
    status: 'У дилера',
    dealer: 'ОПТИМА',
    color: 'Серебристый',
    vin: 'EDEFB32B*SE****80',
  },
  {
    id: 'vin-EDEFB32B*SE****17',
    name: 'Tenet T7',
    price: 2830000,
    monthly: 0,
    info: '1 автомобиль',
    images: [PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')!],
    gearbox: 'робот',
    bodyType: 'внедорожник',
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: 'Prime',
    year: 2024,
    engineVolume: '1.6',
    transmission: 'Робот',
    drivetrain: 'Передний привод',
    status: 'У дилера',
    dealer: 'ОПТИМА',
    color: 'Искрящийся белый',
    vin: 'EDEFB32B*SE****17',
  },
  {
    id: 'vin-EDEFB32B*SE****44',
    name: 'Tenet T7',
    price: 2830000,
    monthly: 0,
    info: '1 автомобиль',
    images: [PlaceHolderImages.find(p => p.id === 'tenet-t7-white-1')!],
    gearbox: 'робот',
    bodyType: 'внедорожник',
    count: 1,
    seats: 7,
    specs: [],
    trims: [],
    trimName: 'Prime',
    year: 2024,
    engineVolume: '1.6',
    transmission: 'Робот',
    drivetrain: 'Передний привод',
    status: 'У дилера',
    dealer: 'ОПТИМА',
    color: 'Искрящийся белый',
    vin: 'EDEFB32B*SE****44',
  },
  {
    id: 'vin-EDEEB31B*SE****30-2',
    name: 'Tenet T4',
    price: 2250000,
    monthly: 0,
    info: '1 автомобиль',
    images: [PlaceHolderImages.find(p => p.id === 'tenet-t4-white-1')!],
    gearbox: 'робот',
    bodyType: 'внедорожник',
    count: 1,
    seats: 5,
    specs: [],
    trims: [],
    trimName: 'Active',
    year: 2024,
    engineVolume: '1.5T',
    transmission: 'Робот',
    drivetrain: 'Передний привод',
    status: 'У дилера',
    dealer: 'ОПТИМА',
    color: 'Искрящийся белый',
    vin: 'EDEEB31B*SE****30',
  }
].filter(car => car.color);

    


